### PR TITLE
Update a.txt

### PR DESCRIPTION
**Pull request by KakanotCollaborator**

### CODE REVIEW

**Comment by codekaka** [comment]
Pull request was made succesfully and this is a small sized commit. Do you still want me to run analysis? 

```
                    Reply with run all if you want to run.
```

**Comment by chethan1801** [comment]
@codekaka a

**Comment by codekaka** [comment]
Do you want me to run any or all of the following analysis?

s1: Code coverage
                    s2: Code Duplication
                    s3: Dependency Analysis
                    s4: Documentation
                    run all: To run all the above analysis

Please reply with s1, s2, s3, s4 or 'run all' for the respective analysis
                    Example 1: To run Code coverage, Code Duplication, reply with "run s1,s2"
                    Example 2: To run all the analysis, reply with "run all".
                    Note: Reply commands are not case sensitive.

**Comment by chethan1801** [comment]
@codekaka run all

**Comment by codekaka** [comment]
Ran all the analysis and here are the results

##    COVERAGE

/src/path/to/file1/             43 %
/src/path/to/file2/             39 %
/src/path/to/file3/             73 %
/src/path/to/file4/             98 %
/src/path/to/file5/             54 %
/src/path/to/file6/             71 %

## Dependency Changes:
- boto.py
- pygithub.py
- pyunit

## Found these duplicates:

[1] ....
[2] ....

## DOCUMENTATION

@Class_M :
/*\* ....
-   ....
-   ....
  */

@method_A :
// ....
// ....
// ....

@method_B :
// ....
// ....
// ....

**Comment by codekaka** [comment]
Pull request was made succesfully and this is a small sized commit. Do you still want me to run analysis? 

```
                    Reply with run all if you want to run.
```

**Pull request closed without merging**
